// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcxWZmbRUjM_hjGAcDtj08mdfyccLfJ5c',
    appId: '1:898260213564:web:857357db4ea98fed8fc839',
    messagingSenderId: '898260213564',
    projectId: 'mada-guide-touristique',
    authDomain: 'mada-guide-touristique.firebaseapp.com',
    storageBucket: 'mada-guide-touristique.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4ZdmnXgkN0ZDcCsMmPLCKAl2kLqNxYks',
    appId: '1:898260213564:android:4b7a69fe7ec6d7ba8fc839',
    messagingSenderId: '898260213564',
    projectId: 'mada-guide-touristique',
    storageBucket: 'mada-guide-touristique.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYI1MrSf0orWNWXENzoMYhxTveZO17A4k',
    appId: '1:898260213564:ios:d9e98746c7753ab88fc839',
    messagingSenderId: '898260213564',
    projectId: 'mada-guide-touristique',
    storageBucket: 'mada-guide-touristique.firebasestorage.app',
    iosBundleId: 'com.example.guideTouristiqueAugmente',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYI1MrSf0orWNWXENzoMYhxTveZO17A4k',
    appId: '1:898260213564:ios:d9e98746c7753ab88fc839',
    messagingSenderId: '898260213564',
    projectId: 'mada-guide-touristique',
    storageBucket: 'mada-guide-touristique.firebasestorage.app',
    iosBundleId: 'com.example.guideTouristiqueAugmente',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcxWZmbRUjM_hjGAcDtj08mdfyccLfJ5c',
    appId: '1:898260213564:web:603bdfcaae7542268fc839',
    messagingSenderId: '898260213564',
    projectId: 'mada-guide-touristique',
    authDomain: 'mada-guide-touristique.firebaseapp.com',
    storageBucket: 'mada-guide-touristique.firebasestorage.app',
  );
}
